name: Update Revenue

on:
  schedule:
    - cron: '*/10 * * * *'    # каждые 10 минут
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Create folders
        run: mkdir -p data/daily

      - name: Run script
        run: python revenue_server.py

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/revenue.json data/daily/
          git commit -m "Update $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
